# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
puts "Start seeding..."

Recipe.create(title: "Punjabi Rajma Masala", description: "Red kidney bean curry with garlic, black pepper and Knorr smoked tomato chilli pots", photo: "https://images.unsplash.com/photo-1596797038530-2c107229654b?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=975&q=80")
Recipe.create(title: "Saffron Pulao", description: "With cardamom, cinnamon and basmati rice. A really simple rice based recipe that is a brilliant accompaniment to an Indian meal. Saffron lends a lovely colour and flavour to this pulao along with the whole spices I have used. Use good quality saffron while cooking", photo: "https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1951&q=80")
Recipe.create(title: "Bengali Phulkopir Aloo Dalna", description: "Spiced cauliflower and potato curry with whole spices, turmeric and green peas", photo: "https://images.unsplash.com/photo-1551881192-002e02ad3d87?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80")
Recipe.create(title: "Garlic Naan", description: "Indian flat bread with ghee, coriander and fried garlic", photo: "https://images.unsplash.com/photo-1586524068358-77d2196875e7?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=934&q=80")
Recipe.create(title: "Gobi Manchurian", description: "Fried crispy cauliflower coated in a garlic, chilli and soy sauce", photo: "https://images.unsplash.com/photo-1598233847491-f16487adee2f?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=1601&q=80")
Recipe.create(title: "Gujarati Ringan batata nu shaak", description: "Spicy Aubergine and potato curry", photo: "https://images.unsplash.com/photo-1593329344473-6a9dfc15dc3d?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=2902&q=80")
Recipe.create(title: "Kumpir", description: "In Turkey, this staple street food item is prepared with a whole baked potato that is cut through the middle and comes filled with a combination of puréed potatoes, butter, and kaşar cheese. The potatoes are usually large in size, baked with their skin intact, while the toppings may include mayonnaise or ketchup and anything from fresh or pickled vegetables to salads and sausages.", photo: "https://images.unsplash.com/photo-1543340713-1bf56d3d1b68?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1919&q=80")
Recipe.create(title: "Onion Samosa", description: "One of India's most popular deep-fried snacks. This particular variety is stuffed with a savory filling of sliced onions (and sometimes also cabbage and rice flakes) which are seasoned with a variety of spices such as red chili powder, poha, and coriander.", photo: "https://images.unsplash.com/photo-1601050690597-df0568f70950?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80")


Recipe.create(title: "Salad Variations", description: "Whats better then a fresh Salad on warm summer days or as a starter? I love to chop every green I get and display them nicely.Make this salad for your next picnic, and it’ll be a guaranteed hit. A tahini miso dressing gives it a creamy umami coating, while peaches add juicy pops of sweetness. I finish it with toasted pepitas for crunch.", photo: "https://images.unsplash.com/photo-1498837167922-ddd27525d352?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=1350&q=80")
Recipe.create(title: "Green Buddha Bowl", description: "Mix your favorite vegetables with some protein food like chickpeas, add some nice dressing and enjoy your healthy lunch break! I love to add naan to it.", photo: "https://images.unsplash.com/photo-1511690656952-34342bb7c2f2?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MTF8fGZvb2R8ZW58MHx8MHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60")
Recipe.create(title: "Everyone's favorite breakfast", description: "We never grow old loving this breakfast! Warm toast with blueberries and banana slices and some warm maple syrup on top. Recommended for morning blues!", photo: "https://images.unsplash.com/photo-1484723091739-30a097e8f929?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MTd8fGZvb2R8ZW58MHx8MHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60")
Recipe.create(title: "Sweet decorated cakes", description: "If you wanna have fun with your girls, have loads of fruits available and a lot of phantasy to create something like that!", photo: "https://images.unsplash.com/photo-1495147466023-ac5c588e2e94?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MjR8fGZvb2R8ZW58MHx8MHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60")
Recipe.create(title: "Chinese Dumblings", description: "Dumblings filled with vegetables, served with soya sauce. Those little crispy pan fried bottoms and perfectly steamed filling/tops? Better get a double order of them, because I am eating them all! But this shouldn’t be a surprise to any of you, seeing as my other favorite dinner includes dumplings as well.", photo: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxzZWFyY2h8Mzh8fGZvb2R8ZW58MHx8MHw%3D&auto=format&fit=crop&w=500&q=60")

puts "End seeding, #{Recipe.count} created..."
